setwd("~/Userdata/Personal/Data Science/RDir")
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip","Energy_Consumption.zip")
unzip("Energy_Consumption.zip",list = FALSE,unzip = "internal")
energy_file<- read.table("household_power_consumption.txt",header=TRUE,sep = ";", na.strings = "?", stringsAsFactors = FALSE)
energy_file_subset<-subset(energy_file, Date %in% c("1/2/2007","2/2/2007"))
energy_file_subset$Date<-as.Date(energy_file_subset$Date, "%d/%m/%y")
png(file="Plot1.png",width = 480,height = 480)
hist(energy_file_subset$Global_active_power,main="Global Active Power", col="red", xlab = "Global Active Power (kilowatts)")
dev.off()
